// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpOTPCJ5LxF_H5oqKlqbGrSGGItjNfp5c',
    appId: '1:367980199883:web:e89f8aa5412181e717804e',
    messagingSenderId: '367980199883',
    projectId: 'anveshana-121f4',
    authDomain: 'anveshana-121f4.firebaseapp.com',
    storageBucket: 'anveshana-121f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aH9b8ggZaB7kRFUOVCXOYyIxR6AooOo',
    appId: '1:367980199883:android:a5da19200ca534fe17804e',
    messagingSenderId: '367980199883',
    projectId: 'anveshana-121f4',
    storageBucket: 'anveshana-121f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_04hv3jcnOgfgIvuQxH_W8CYA8KNzyE',
    appId: '1:367980199883:ios:2bb42a5342c7b9fb17804e',
    messagingSenderId: '367980199883',
    projectId: 'anveshana-121f4',
    storageBucket: 'anveshana-121f4.appspot.com',
    iosClientId: '367980199883-ftd3n7dv9e173c6njdgvifa34907mris.apps.googleusercontent.com',
    iosBundleId: 'com.example.anveshana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1_04hv3jcnOgfgIvuQxH_W8CYA8KNzyE',
    appId: '1:367980199883:ios:2bb42a5342c7b9fb17804e',
    messagingSenderId: '367980199883',
    projectId: 'anveshana-121f4',
    storageBucket: 'anveshana-121f4.appspot.com',
    iosClientId: '367980199883-ftd3n7dv9e173c6njdgvifa34907mris.apps.googleusercontent.com',
    iosBundleId: 'com.example.anveshana',
  );
}
