// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOViw6kLc0xS4n1eHRjL7Tt7bkUL5UZJo',
    appId: '1:151655869902:web:8704a0a90e8352b671cf9f',
    messagingSenderId: '151655869902',
    projectId: 'anveshana-6e3ca',
    authDomain: 'anveshana-6e3ca.firebaseapp.com',
    storageBucket: 'anveshana-6e3ca.appspot.com',
    measurementId: 'G-2SBXQXZDQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_wrZe8RWh-2feWVcG-rCoMuRbGkjoDk',
    appId: '1:151655869902:android:81cc768a9c0a94ee71cf9f',
    messagingSenderId: '151655869902',
    projectId: 'anveshana-6e3ca',
    storageBucket: 'anveshana-6e3ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC9EC6jferajIn5w1FF9u5TTAgS7xua1g',
    appId: '1:151655869902:ios:de222739a8a12bd171cf9f',
    messagingSenderId: '151655869902',
    projectId: 'anveshana-6e3ca',
    storageBucket: 'anveshana-6e3ca.appspot.com',
    iosClientId: '151655869902-ku5e9iplgut24himqqo52fjf90840gnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.anveshana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC9EC6jferajIn5w1FF9u5TTAgS7xua1g',
    appId: '1:151655869902:ios:de222739a8a12bd171cf9f',
    messagingSenderId: '151655869902',
    projectId: 'anveshana-6e3ca',
    storageBucket: 'anveshana-6e3ca.appspot.com',
    iosClientId: '151655869902-ku5e9iplgut24himqqo52fjf90840gnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.anveshana',
  );
}
